"""DjokRev

Revision ID: 5cb0fa266a26
Revises: 7c612fcab159
Create Date: 2023-11-19 01:50:52.921558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cb0fa266a26'
down_revision: Union[str, None] = '7c612fcab159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ticket_messages', type_='foreignkey')
    op.create_foreign_key(None, 'ticket_messages', 'tickets', ['ticket_id'], ['id'])
    op.drop_column('ticket_messages', 'createdAt')
    op.drop_column('ticket_messages', 'sendTo')
    op.drop_column('ticket_messages', 'ticket')
    op.add_column('tickets', sa.Column('prior', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'prior')
    op.add_column('ticket_messages', sa.Column('ticket', sa.INTEGER(), nullable=True))
    op.add_column('ticket_messages', sa.Column('sendTo', sa.VARCHAR(), nullable=True))
    op.add_column('ticket_messages', sa.Column('createdAt', sa.TIME(), nullable=True))
    op.drop_constraint(None, 'ticket_messages', type_='foreignkey')
    op.create_foreign_key(None, 'ticket_messages', 'tickets', ['ticket'], ['id'])
    # ### end Alembic commands ###
